sources:
  ibmi-system:
    host: ${DB2i_HOST}
    user: ${DB2i_USER}
    password: ${DB2i_PASS}
    port: 8076
    ignore-unauthorized: true

tools:
  count_exposed_profiles:
    source: ibmi-system
    description: "How many *USRPRF's do not have *PUBLIC set to *EXCLUDE?"
    parameters:
      - name: excludeSystemProfiles
        type: boolean
        default: true
        description: "Exclude system profiles from count"
    statement: |
      SELECT COUNT(*) as exposed_count
      FROM qsys2.object_privileges
      WHERE system_object_schema = 'QSYS' 
        AND object_type = '*USRPRF' 
        AND user_name = '*PUBLIC' 
        AND object_authority <> '*EXCLUDE'
        {{#if excludeSystemProfiles}}
        AND object_name NOT IN ('QDBSHR', 'QDBSHRDO', 'QDOC', 'QTMPLPD')
        {{/if}}

  list_exposed_profiles:
    source: ibmi-system
    description: "Which *USRPRF's do not have *PUBLIC set to *EXCLUDE?"
    parameters: []
    statement: |
      SELECT object_name AS user_name, 
             object_authority
      FROM qsys2.object_privileges
      WHERE system_object_schema = 'QSYS' 
        AND object_type = '*USRPRF' 
        AND object_name NOT IN ('QDBSHR', 'QDBSHRDO', 'QDOC', 'QTMPLPD') 
        AND user_name = '*PUBLIC' 
        AND object_authority <> '*EXCLUDE'
      ORDER BY object_name

  user_profile_analysis:
    source: ibmi-system
    description: "Get detailed information about a specific user profile"
    parameters:
      - name: username
        type: string
        description: "User profile name to analyze"
    statement: |
      SELECT 
        *
      FROM qsys2.user_info 
      WHERE authorization_name = UPPER('{{username}}')

  recent_signons:
    source: ibmi-system
    description: "List all users who have signed on in the past day"
    parameters: []
    statement: |
      SELECT 
          authorization_name,
          previous_signon,
          status,
        text_description
      FROM qsys2.user_info 
      WHERE previous_signon >= CURRENT_TIMESTAMP - 1 DAY
        AND previous_signon IS NOT NULL
      ORDER BY previous_signon DESC
      
toolsets:
  security:
    tools:
      - count_exposed_profiles
      - list_exposed_profiles
      - user_profile_analysis
      - recent_signons