[project]
name = "ibmi-agent-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adam Shedivy", email = "ajshedivyaj@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "agno>=2.1.0",
    "mcp>=1.16.0",
]

[project.scripts]
ibmi-agent-sdk = "ibmi_agent_sdk:main"

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
